Remove CAS and post-build verification

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,23 +17,23 @@ runs:
         fi
         echo "version=${input}" >> "$GITHUB_OUTPUT"
 
-    - uses: home-assistant/actions/helpers/cas@master
+#    - uses: home-assistant/actions/helpers/cas@master
 
     - shell: bash
       run: |
         docker pull ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}
 
-    - shell: bash
-      run: |
-        for j in {1..15}; do
-          if CAS_API_KEY= cas authenticate --silent --signerID notary@home-assistant.io docker://ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}; then
-            exit 0
-          fi
-          sleep $((5 * j))
-        done
+#    - shell: bash
+#      run: |
+#        for j in {1..15}; do
+#          if CAS_API_KEY= cas authenticate --silent --signerID notary@home-assistant.io docker://ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}; then
+#            exit 0
+#          fi
+#          sleep $((5 * j))
+#        done
 
-        echo "Invalid signature!"
-        exit 1
+#        echo "Invalid signature!"
+#        exit 1
 
     - shell: bash
       id: builder
@@ -55,14 +55,14 @@ runs:
             ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} \
             ${{ inputs.args }}
 
-    - shell: bash
-      id: verify
-      run: |
-        docker images \
-          --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}" \
-          --filter reference="*/*" \
-          --filter reference="*" \
-          --filter since=${{ steps.builder.outputs.id }}
+#    - shell: bash
+#      id: verify
+#      run: |
+#        docker images \
+#          --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}" \
+#          --filter reference="*/*" \
+#          --filter reference="*" \
+#          --filter since=${{ steps.builder.outputs.id }}
 branding:
   icon: "home"
   color: "blue"
